const fs = require('fs');
let dir = './';
let fileCreator = {
    create: function (type, name, specify) {
        if (this.directoryManager.folder(type, this.flcase(name))) {
            this.directoryManager.version(type, this.flcase(name),specify);
            console.log('writing...');
            return true;
        } else if(typeof specify !== 'undefined'){
            console.log(dir + type + '/' + this.flcase(name)+'/'+this.fucase(name)+'.ctrl.php');
            console.log(fs.existsSync(dir + type + '/' + this.flcase(name)+'/'+this.fucase(name)+'.ctrl.php'));
            if(specify !== 'custom' && fs.existsSync(dir + type + '/' + this.flcase(name)+'/'+this.fucase(name)+'.ctrl.php')){
                console.log('I don\'t dare to create such a hybrid. Please proceed manually.');
            } else {
                if(this.modifyVersion(name,type)){
                    console.log('writing...');
                    return true;
                } else {
                    console.log('Uh, I am afraid to overwrite important stuff. Please proceed manually.');
                }
            }

        }
        return false;
    },
    frame: function (name) {
        if (this.create('frame', name)) {
            this.php.namespace('Frame');
            this.php.use('Core\\Serve');
            this.php.class(name, 'Serve');
            this.php.closingCurly();
            this.writeToFile(name, 'frame');
        }
    },
    model: function (name) {
        if (this.create('model', name)) {
            this.php.namespace('Model');
            this.php.class(name+'Model', 'IndexModel');
            this.php.classFunction('byId', '', '$id', 'static');
            this.php.classFunction('find', '', '$condition', 'static');
            this.php.closingCurly();
            this.writeToFile(name, 'model');
            fs.appendFile(dir + '/model/' + this.flcase(name) + '/migrate.json', '{}', function (err) {
                if (err) throw err;
            });
        }
    },
    component: function (name, cType, answer) {
        if (this.create('component', name, cType)) {
            let propagatePHP = true;
            this.php.namespace('Components');

            switch (cType) {
                case 'route':
                    this.php.use('Core\\Unicore');
                    this.php.class(name, 'Unicore');
                    let inner = "$this->uni()->";
                    if (answer.frame) {
                        inner = "$this->uni('" + answer.frame + "')->";
                    }
                    if (answer.hasView) {
                        this.htmlView(name);
                        inner += "hook('main','" + this.flcase(name) + "')->";
                    }
                    this.php.classFunction('init', inner + "output();");
                    break;
                case 'api':
                    this.php.use('Frame\\' + this.fucase(answer.frame));
                    this.php.class(name, this.fucase(answer.frame));
                    this.php.classFunction('get' + this.fucase(name), "", "$obj");
                    this.php.classFunction('post' + this.fucase(name), "", "$obj");
                    break;
                case 'custom':
                    propagatePHP = false;
                    this.ce.writeJs(name);
                    break;
            }
            this.php.closingCurly();
            if(propagatePHP){
                this.writeToFile(name, 'component');
            }
        }

    },
    ce: {
        fileString:'',
        writeJs: function (name) {
            fs.appendFile(dir + 'component/' + fileCreator.flcase(name) + '/' + fileCreator.flcase(name) +'.ce.js', this.fileString, function (err) {
                if (err) throw err;
            });
        }
    },
    php: {
        fileString: false,
        init: function () {
            if (!this.fileString) {
                this.fileString = "<?php\n/* Generated by neoan3-cli */\n\n";
            }
        },
        indentation: function (x) {
            this.fileString += "    ".repeat(x);

        },
        namespace: function (type) {
            this.init();
            this.fileString += "namespace Neoan3\\" + type + ";\n\n";
        },
        use: function (str) {
            this.init();
            this.fileString += "use Neoan3\\" + str + ";\n"
        },
        class: function (name, extend) {
            this.init();
            this.fileString += "\nclass " + fileCreator.fucase(name);
            if (typeof extend !== 'undefined') {
                this.fileString += " extends " + fileCreator.fucase(extend);
            }
            this.fileString += " {\n";
        },
        classFunction: function (name, inner, arg, typus = 'public') {
            this.init();
            this.indentation(1);
            if (typus === 'public') {
                this.publicFunction(name, arg);
            } else if (typus === 'static') {
                this.staticFunction(name, arg);
            }
            this.indentation(2);
            this.fileString += inner + "\n";
            this.indentation(1);
            this.closingCurly();
            this.fileString += "\n";
        },
        staticFunction: function (fname, arg) {
            this.init();
            this.fileString += "static function " + fname + "(" + (arg ? arg : '') + "){\n";
        },
        publicFunction: function (fname, arg) {
            this.init();
            this.fileString += "function " + fname + "(" + (arg ? arg : '') + "){\n";
        },
        closingCurly: function () {
            this.fileString += "}\n";
        }
    },
    htmlView: function (name) {
        fs.writeFile(dir + 'component/' + this.flcase(name) + '/' + this.flcase(name) + '.view.html', '<h1>' + name + '</h1>', function (err, outd) {
            if (err) {
                throw new Error(err);
            }
        });
    },
    htaccess: function (base) {
        let content = fs.readFileSync('./.htaccess', 'utf8');
        let newContent = content.replace(/RewriteBase\s\/[a-z0-9\/-]+/im, function (x) {
            return 'RewriteBase /' + base + '/';
        });
        fs.writeFile('./.htaccess', newContent, function (err, outd) {
            if (err) {
                throw new Error(err);
            }
        });

    },
    writeToFile: function (name, type) {
        let localExt;
        switch (type) {
            case 'component':
                localExt = '.ctrl.php';
                break;
            case 'model':
                localExt = '.model.php';
                break;
            default:
                localExt = '.php';
                break;
        }
        let loType = this.fucase(type);
        fs.appendFile(dir + type + '/' + this.flcase(name) + '/' + fileCreator.fucase(name) + localExt, this.php.fileString, function (err) {
            if (err) throw err;
            console.log('%s %s created', loType, name);
        });
    },
    fucase: function (string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
    },
    flcase: function (string) {
        return string.charAt(0).toLowerCase() + string.slice(1);
    },
    directoryManager: {
        folder: function (type, name) {
            if (!fs.existsSync(dir + type + '/' + name)) {
                fs.mkdirSync(dir + type + '/' + name);
                return true;
            } else {
                console.log('Notice: %s %s already exists', type, name);
                return false;
            }
        },
        version: function (type, name, specify) {
            fs.appendFile(dir + type + '/' + name.toLowerCase() + '/version.json', fileCreator.versionJson(name,type,specify), function (err) {
                if (err) throw err;
            });
        }
    },
    modifyVersion: function(name,type){
        let version = JSON.parse(fs.readFileSync(dir + type + '/' + name.toLowerCase() + '/version.json','utf8'));
        if(typeof version.type !== 'undefined' && version.type === 'hybrid'){
            return false;
        }
        version.type = 'hybrid';
        fs.writeFile(dir + type + '/' + name.toLowerCase() + '/version.json', JSON.stringify(version, null, 4), function (err) {
            if (err) throw err;
        });
        return true;
    },
    versionJson: function (name,type,specify) {
        if(typeof specify !== 'undefined'){
            type = specify;
        }
        let json = {"version": "0.0.1", "name": name,"type":type};
        return JSON.stringify(json, null, 4);
    },
};
module.exports = fileCreator;
